<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<? $this->headlink()->appendStylesheet('/css/screen.css' , 'screen, projection'); ?>
		<? $this->headlink()->appendStylesheet('/css/ie.css' , 'screen, projection' , 'IE'); ?>
		<? $this->headlink()->appendStylesheet('/css/print.css' , 'print'); ?>
		<? $this->headlink()->appendStylesheet('/css/main.css'); ?>

		<?= $this->headlink(); ?>
		<?= $this->headScript()->appendFile('/js/jquery.js'); ?>
	</head>
	<body>
		<div class="container" >
		<div class="header">
			<h1>
				Introduction to Unit testing
			</h1>
		</div>
			<div class="push-1 span-14 maincontent">
				<?= $this->layout()->content; ?>
			</div>
			
		</div>

	</body>
</html>