<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />


		<? $this->headLink()->appendStylesheet('/css/screen.css' , 'screen, projection'); ?>
		<? $this->headLink()->appendStylesheet('/css/ie.css' , 'screen, projection' , 'IE'); ?>
		<? $this->headLink()->appendStylesheet('/css/print.css' , 'print'); ?>
		<? $this->headLink()->appendStylesheet('/css/main.css'); ?>

		<?= $this->headLink(); ?>
		<?= $this->headScript()->appendFile('/js/jquery.js'); ?>
	</head>
	<body>
		<div class="container" >
			<div class="push-1 span-14 maincontent">
				<?= $this->layout()->content; ?>
			</div>
			
		</div>

	</body>
</html>